export const ACTION_CLOSE_DIALOG = 'CLOSE_DIALOG';
export const ACTION_OPEN_DIALOG = 'OPEN_DIALOG';
export const ACTION_COMMIT_VALUE = 'ACTION_COMMIT_VALUE_CHANGE';
export const ACTION_REVERT_VALUE = 'ACTION_REVERT_VALUE_CHANGE';
export const ACTION_SET_VALUE = 'ACTION_SET_VALUE';
