export const ACTION_CLICK_NEXT_MONTH = 'ACTION_CLICK_NEXT_MONTH';
export const ACTION_CLICK_DAY = 'CLICK_DAY';
export const ACTION_CLICK_PREV_MONTH = 'ACTION_CLICK_PREV_MONTH';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const MOUSE_ENTER_DAY = 'MOUSE_ENTER_DAY';
export const MOUSE_LEAVE_DAY = 'MOUSE_LEAVE_DAY';
export const CHANGE_VIEW = 'CHANGE_VIEW';

